### ISSUE TITLE
Suggestion - Allow the player to choose respawning near death or bed

### ISSUE THREAD

**Issue by InteJason** [henkelmax/better-respawn#5] opened 2021-01-20 18:56 UTC
If the player tries to respawn near the death location and gets killed a couple of times., they might wanna respawn near their beds instead. This would be a cool function to add I think.

Thanks for your time :)

**Comment by henkelmax** [comment] 2021-01-20 19:58
Duplicate of #4

**Closed as completed by henkelmax** 2021-01-20 19:58 UTC
Labels: enhancement
